# server:
#   port: 9999
# spring:
#   application:
#     name: api-gateway
#   cloud:
#     gateway:
#       discovery:
#         locator:
#           enabled: true
#           lower-case-service-id: true
#       routes:
#         - id: admin-service-auth
#           uri: lb://admin-service
#           predicates:
#             - Path=/api/auth/**
#           filters:
#             - JwtAuthenticationFilter  # No "name:" prefix needed
#         - id: admin-service-admin
#           uri: lb://admin-service
#           predicates:
#             - Path=/api/admin/**
#           filters:
#             - JwtAuthenticationFilter
#             - StripPrefix=1          # Keep this as it was
#         - id: timetable-service
#           uri: lb://timetable-service
#           predicates:
#             - Path=/api/timetable-service/**
#         - id: calendar-service  # New route for calendar-service
#           uri: lb://calendar-service
#           predicates:
#             - Path=/api/calendar/**
#           filters:
#             - JwtAuthenticationFilter  # Secure the endpoint
#             - StripPrefix=1  # Remove "/api" from the path
#       globalcors:
#         cors-configurations:
#           '[/**]':
#             allowedOrigins: "http://localhost:4200"
#             allowedMethods:
#               - GET
#               - POST
#               - PUT
#               - DELETE
#               - OPTIONS
#             allowedHeaders: "*"
#             allowCredentials: true
#             maxAge: 3600
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     leaseRenewalIntervalInSeconds: 30
#     leaseExpirationDurationInSeconds: 90
# jwt:
#   secret: X7K9p2mQ8vL5rT3yZn6bQeF4uA1wJ9kLmN5oP6sR7tU8vW9xY0z1aB2c3d4E5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6A7B8C9D
# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG
#     tn.esprit.apigateway: DEBUG




# server configuration
server:
  port: 9999

# Spring application configuration
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: admin-service-auth
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/auth/**
          # No StripPrefix here, so /api/auth/login stays intact
        - id: admin-service-admin
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=1  # Strip /api for admin endpoints
        - id: timetable-service
          uri: lb://TIMETABLE-SERVICE
          predicates:
            - Path=/api/timetable-service/**
          filters:
            - StripPrefix=2
        - id: calendar-service
          uri: lb://CALENDAR-SERVICE
          predicates:
              - Path=/api/calendar-service/**
          filters:
              - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://frontend.time4class.com:30080"
              - "http://192.168.157.131:30001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://10.200.1.203:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

# JWT secret key
jwt:
  secret: X7K9p2mQ8vL5rT3yZn6bQeF4uA1wJ9kLmN5oP6sR7tU8vW9xY0z1aB2c3d4E5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6A7B8C9D

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    reactor.netty: TRACE
    org.springframework.web: TRACE
    org.springframework.http: TRACE
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

